const source = new URL(
  "../node_modules/@phosphor-icons/web/src/duotone/style.css",
  import.meta.url,
)
const target = new URL("../shared/models/BoardIconCatalog.ts", import.meta.url)
const css = await Bun.file(source).text()
const icons = [
  ...new Set(
    [...css.matchAll(/\.ph-duotone\.ph-(?<name>[a-z0-9-]+):before/g)].map(
      (match) => match.groups!.name,
    ),
  ),
].toSorted()

await Bun.write(
  target,
  `// Generated by scripts/generate-board-icons.ts. Do not edit manually.\nexport const BoardIconCatalog = ${JSON.stringify(icons, null, 2)} as const\n`,
)

console.log(`Generated ${icons.length} Board icon keys.`)
